<?php
/**
 * Main Function
 *
 * Load functions and classes
 *
 * @package      responsive_mobile
 * @license      license.txt
 * @copyright    2014 CyberChimps Inc
 * @since        0.0.1
 *
 * Please do not edit this file. This file is part of the responsive_mobile Framework and all modifications
 * should be made in a child theme.
 */
 
 function remove_wp_version_rss() {
return '';
}
add_filter('the_generator', 'remove_wp_version_rss');
/** sposób płatności a wysyłka **/

/**
 * Filter payment gateways
 */
function my_custom_available_payment_gateways( $gateways ) {
	$chosen_shipping_rates = WC()->session->get( 'chosen_shipping_methods' );

		if ( in_array( 'flat_rate:1', $chosen_shipping_rates ) ) :
		unset( $gateways['cod'] );
		
		elseif ( in_array( 'flat_rate:2', $chosen_shipping_rates ) ) :
		unset( $gateways['bacs'] );
		
		elseif ( in_array( 'flat_rate:3', $chosen_shipping_rates ) ) :
		unset( $gateways['cod'] );
		
		elseif ( in_array( 'flat_rate:4', $chosen_shipping_rates ) ) :
		unset( $gateways['bacs'] );

	endif;
	return $gateways;
}
add_filter( 'woocommerce_available_payment_gateways', 'my_custom_available_payment_gateways' );

 /** Dodatkowe menu **/
 
register_nav_menu( 'user-menu', 'Menu Użytkownika' );

/**add_theme_support( 'wc-product-gallery-zoom' );**/
add_theme_support( 'wc-product-gallery-lightbox' );
/**add_theme_support( 'wc-product-gallery-slider' );**/


/** ceny od **/

add_filter('woocommerce_variable_price_html', 'custom_variation_price', 10, 2);
function custom_variation_price( $price, $product ) {
$price = '';
if ( !$product->min_variation_price || $product->min_variation_price !== $product->max_variation_price ) {
$price .= '<span class="Od">' . _x('Od', 'min_price', 'woocommerce') . ' </span>';
$price .= woocommerce_price($product->get_price());
}
return $price;
}

 
/** **/

remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_excerpt', 20 );
add_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_excerpt', 5 );

remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_meta', 40 );
add_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_meta', 4 );
/** **/ 

remove_action( 'woocommerce_after_single_product_summary', 'woocommerce_output_related_products', 20 );


add_filter( 'woocommerce_product_tabs', 'woo_remove_product_tabs', 97 );

function woo_remove_product_tabs( $tabs ) {


    unset( $tabs['additional_information'] );  	// Remove the additional information tab

    return $tabs;

}

add_filter( 'woocommerce_product_tabs', 'woo_rename_tabs', 98 );
function woo_rename_tabs( $tabs ) {

	$tabs['description']['title'] = __( 'Szczegółowy opis' );		// Rename the description tab
	$tabs['reviews']['title'] = __( 'Opinie klientów' );				// Rename the reviews tab
	

	return $tabs;

}

 
 
 
function woocommerce_show_empty_categories($show_empty){
    return true;
}
 
// If this file is called directly, abort.

// Display variations dropdowns on shop page for variable products

function main( $items, $args ) {

    // Checks to see if the menu passed in is the primary one, and creates the logo item for it
    if ( $args->theme_location == 'primary' ) {
        $logo_item = '<li class="menu-item">LOGO TUTAJ</li>';
    }

    //Gets the location of the menu element I want to insert the logo before
    $index = round( count_top_lvl_items() / 2 ) + 1;
    //Gets the menu item I want to insert the logo before
    $menu_item = get_menu_item( $index );
    $insert_before = '<li id="menu-item-' . $menu_item->ID;

    $menu_update = substr_replace( $items, $logo_item, strpos( $items, $insert_before ), 0 );

    return $new_menu;
}

//Counts the number of top level items in the menu
function count_top_lvl_items() {
    $items = get_menu_items();
    $counter = 0;
    foreach ( $items as $val ) {
        if ( $val->menu_item_parent === '0' ) {
            $counter++;
        {
    return $counter;
}
		}
	}
}

//Returns the menu item to insert the logo before
function get_menu_item( $index ) {
    $items = get_menu_items();
    $counter = 0;
    foreach ( $items as $val ) {
        if ( $val->menu_item_parent === '0' ) {
            $counter++;
        }
        if ( $counter == $index ) {
            return $val;
        }
    }
}

//Returns the logo menu item. I have it separated because my theme allows for varied logos
function get_logo() {
   // $home = get_option( 'home' );
   // $logo = get_option( 'logo' );
    $logo_item = <<<EOD

        <div id="logo">
            <a href="$home">
                <img src="$logo" id="logo-img" alt=""/> logo tutaj
            </a>
        </div>
EOD;

    return $logo_item;
}

function get_menu_items() {
    $locations = get_nav_menu_locations();
    $menu = wp_get_nav_menu_object( $locations['primary'] );
    $items = wp_get_nav_menu_items( $menu );
    return $items;
}


