<?php
/**
 * Header
 *
 * Displays all information in head, starts the body tag, contains theme header
 * and nav and starts the main content wrapper
 *
 * @package      responsive_mobile
 * @license      license.txt
 * @copyright    2014 CyberChimps Inc
 * @since        0.0.1
 *
 * Please do not edit this file. This file is part of the responsive_mobile Framework and all modifications
 * should be made in a child theme.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}
?>
<!DOCTYPE html>
<!--[if IE 8 ]>
	<html class="no-js ie8" <?php language_attributes(); ?>>
<![endif]-->
<!--[if IE 9 ]>
	<html class="no-js ie9" <?php language_attributes(); ?>>
<![endif]-->
<!--[if gt IE 9]><!-->
<html <?php language_attributes(); ?>><!--<![endif]-->
	<head>
		<?php responsive_mobile_head_top(); ?>
		<meta charset="<?php bloginfo( 'charset' ); ?>">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta http-equiv="X-UA-Compatible" content="IE=9; IE=8; IE=7; IE=EDGE" /> 
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
		<link rel="stylesheet" src="<?php echo get_stylesheet_directory_uri(); ?>/reset.css">
		<link rel="stylesheet" href="<?php echo get_stylesheet_directory_uri(); ?>/font-awesome/css/font-awesome.min.css">
		<link rel="profile" href="http://gmpg.org/xfn/11">
		<link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>">
		<?php responsive_mobile_head_bottom(); ?>
		<?php wp_head(); ?>
		
		<script src="<?php echo get_stylesheet_directory_uri(); ?>/js/search.js"></script>
<script src="<?php echo get_stylesheet_directory_uri(); ?>/js/stickymenu.js"></script>
	</head>
  
<body <?php body_class(); ?> itemscope="itemscope" itemtype="http://schema.org/WebPage">
<?php responsive_mobile_body_top(); ?>
<div id="container" class="site">
	<a class="skip-link screen-reader-text" href="#content"><?php _e( 'Skip to content', 'responsive-mobile' ); ?></a>
	<a class="skip-link screen-reader-text" href="#main-navigation"><?php _e( 'Skip to main menu', 'responsive-mobile' ); ?></a>
<?php
global $current_user;
get_currentuserinfo();				
				
if ( is_user_logged_in() )  { ?>

<?php responsive_mobile_container_top(); ?>
<?php if ( has_nav_menu( 'top-menu', 'responsive-mobile' ) ) { ?>
	<div id="top-menu-container" class="container-full-width">
		<nav id="top-menu" class="container" itemscope itemtype="http://schema.org/SiteNavigationElement">
			<?php wp_nav_menu(
				array(
					'container'      => '',
					'fallback_cb'    => false,
					'menu_class'     => 'top-menu',
					'theme_location' => 'top-menu',
					'depth'          => 1
				)
			); ?>
		</nav>
	</div><!-- top menu container -->
<?php } ?>
<div class="wyszukiwarka top"><?php echo do_shortcode( '[aws_search_form]' ); ?><button class="zamknij" alt="Zamknij okno">zamknij</button></div>
<div class="konto top">
<div class="konto-zamknij"></div><div class="user-info"><?php global $current_user;
      get_currentuserinfo();

      echo 'Witaj <span class="nazwa">' . $current_user->user_login . "</span>\n";
      
?></div>
<?php wp_nav_menu(array('theme_location'=>'user-menu')); ?>


</div>

<div class="koszyk top">
<div class="koszyk-zamknij" alt="Zamknij okno"></div>
<div class="koszyk-srodek">
Twoje zamówienie : 
<!-- KOSZYK / LISTA PRODUKTÓW -->

<?php
    global $woocommerce;
    $items = $woocommerce->cart->get_cart();
		
        foreach($items as $item => $values) { 
		echo "<div class='produkt-jeden'>";
		
            $_product = $values['data']->post; 
			            //product image
			echo "<span class='produkt-img'>";			
            $getProductDetail = wc_get_product( $values['product_id'] );
            //echo $getProductDetail->get_image( 100 ); // accepts 2 arguments ( size, attr )
			echo "</span>";
            echo "<span class='produkt nazwa'>".$_product->post_title.'</span> <span class="produkt ilosc"><strong>Ilość: </strong>'.$values['quantity'].'</span>'; 
            $price = get_post_meta($values['product_id'] , '_price', true);
            echo " <span class='produkt cena'><strong>/ </strong>".$price." zł </span>";
			echo "</div><div style='clear: both; float: none;'></div>";
				
			
        } 
		echo "<div class='pokaz-sume'><strong>Suma : </strong>"; echo sprintf ( _n( '%d produkt', '%d produktów', WC()->cart->get_cart_contents_count() ), WC()->cart->get_cart_contents_count() ); ?> - <?php echo WC()->cart->get_cart_total();
		
		echo " + koszty wysyłki</div><a href='/koszyk/' class='zobacz-koszyk'>Koszyk</a>";
		echo "<a href='/zamowienie/' class='zobacz-zamowienie'>Zamówienia</a>";
	
?>
	  </div> 
</div>

<?php } else { ?>

<?php responsive_mobile_container_top(); ?>
<?php if ( has_nav_menu( 'top-menu', 'responsive-mobile' ) ) { ?>
	<div id="top-menu-container" class="container-full-width">
		<nav id="top-menu" class="container" itemscope itemtype="http://schema.org/SiteNavigationElement">
			<?php wp_nav_menu(
				array(
					'container'      => '',
					'fallback_cb'    => false,
					'menu_class'     => 'top-menu',
					'theme_location' => 'top-menu',
					'depth'          => 1
				)
			); ?>
		</nav>
	</div><!-- top menu container -->
<?php } ?>
<div class="wyszukiwarka top"><?php echo do_shortcode( '[aws_search_form]' ); ?><button class="zamknij">zamknij</button></div>


<?php } ?>	
	
	

<?php responsive_mobile_header_end(); ?>
<div id="menu-top" class="top-menu">
	<div id="main-menu-container" class="container-full-width menu-gorne">
		<div id="main-menu">
		 <!--class="container" --> 
			<nav id="main-navigation" class="site-navigation" role="navigation" itemscope="itemscope" itemtype="http://schema.org/SiteNavigationElement">
				<div id="mobile-current-item"><?php responsive_mobile_menu_title(); ?></div>
				<button id="mobile-nav-button"><span class="accessibile-label"><?php _e( 'Mobile menu toggle', 'responsive-mobile' ); ?></span></button>
				<?php wp_nav_menu(
					array(
						'container'       => 'div',
						'container_class' => 'main-nav',
						'theme_location'  => 'header-menu'
					)
				); ?>
				
				
			</nav><!-- #site-navigation -->
			
		</div><!-- #main-menu -->
	</div><!-- #main-menu-container -->
	<div id="pasek-bottom" class="pasek-dol"></div>
	</div>
<?php responsive_mobile_header_before(); ?>
	<header id="header" class="container-full-width site-header pasek-top" role="banner" itemscope="itemscope" itemtype="http://schema.org/WPHeader">
		<?php responsive_mobile_header_top(); ?>
		<div class="container">
			<div class="header-row">
				<div class="logo-top">
				<a href="<?php echo esc_url( home_url( '/' ) ); ?>" rel="home" itemprop="url"><img src="<?php echo get_stylesheet_directory_uri(); ?>/images/logo-top.jpg"></a>
				</div>
				
			</div>
		</div>

		<?php responsive_mobile_header_bottom(); ?>
	</header><!-- #header -->	
	<?php
		/**$pagename = get_query_var('pagename');**/
		/**if( ( is_front_page()) ) **/
$pagename = get_query_var('pagename');
if( ( is_front_page()) )  {?>

<?php wp_reset_query(); ?>
<div class="blok-slider container-full-width">

<?php 
    echo do_shortcode("[metaslider id=31]"); 
?>


	</div>
			
			
			<?php } else { ?>
			
			<?php } ?>	
<?php responsive_mobile_wrapper(); // before wrapper container hook ?>
	<div id="wrapper" class="site-content container-full-width">
<?php responsive_mobile_wrapper_top(); // before wrapper content hook ?>
<?php responsive_mobile_in_wrapper(); // wrapper hook ?>
